### ISSUE TITLE
hello_world examples not working

### ISSUE THREAD

**Issue by herudi** [timreichen/Bundler#39]
hi, thanks for amazing libs... im try hello_world examples not working on my OS windows. and Deno version 1.10.2.

### Structure
```bash
\---src
        index.html
        index.ts
        world.ts
```

### Command on root hello_world
```bash
 bundler bundle src/index.html=index.html
```

### Error
```bash
Error: file was not found: src\src\world.ts
    at Bundler.readSource (https://deno.land/x/bundler@0.7.1/bundler.ts:92:19)
    at async TypescriptTopLevelAwaitModulePlugin.createAsset (https://deno.land/x/bundler@0.7.1/plugins/typescript/typescript.ts:88:24)
    at async Bundler.createAsset (https://deno.land/x/bundler@0.7.1/bundler.ts:138:23)
    at async Bundler.createGraph (https://deno.land/x/bundler@0.7.1/bundler.ts:218:17)
    at async Bundler.bundle (https://deno.land/x/bundler@0.7.1/bundler.ts:480:19)
    at async bundleFunction (https://deno.land/x/bundler@0.7.1/cli.ts:190:41)
    at async Command.bundleCommand [as fn] (https://deno.land/x/bundler@0.7.1/cli.ts:239:3)
```

* Deno version 1.10.2
* OS Windows 10

Thanks.

**Comment by timreichen** [comment]
Should be fixed now with 0.8.0.
