### ISSUE TITLE
Does not understand .mjs extension / script type

### ISSUE THREAD

**Issue by rotu** [timreichen/Bundler#55]
My index.html file has a script like `<script type="module" src="./main.mjs"></script>`

Bundler crashes because it can't find a createAsset plugin despite (1) mjs being a fairly common extension for JavaScript module files (2) the `type="module"` tag, which [should identify this as Javascript](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type).

```
deno run -A --unstable https://deno.land/x/bundler/cli.ts bundle index.html
Entry index.html
Error: No createAsset plugin found: 'main.mjs'
    at Bundler.createAsset (https://deno.land/x/bundler@0.8.1/bundler.ts:175:11)
    at async Bundler.createGraph (https://deno.land/x/bundler@0.8.1/bundler.ts:251:17)
    at async Bundler.bundle (https://deno.land/x/bundler@0.8.1/bundler.ts:621:19)
    at async bundleFunction (https://deno.land/x/bundler@0.8.1/cli.ts:38:41)
    at async Command.bundleCommand [as fn] (https://deno.land/x/bundler@0.8.1/cli.ts:88:3)
```

**Comment by timreichen** [comment]
multiple extensions are now supported and should be processed correctly with the next release.
