### ISSUE TITLE
Newline behavior

### ISSUE THREAD

**Issue by rotu** [timreichen/Bundler#62]
Many tests are failing on Windows due to differing newlines. What is the expected behavior here (and can it be documented please)?

1. Should test files in the repo have CR or CRLF? If the tests are expected to fail one way, the setting should probably be specified in a [.gitattributes file](https://git-scm.com/docs/gitattributes#_text)
2. Should newlines be normalized by the bundler or left as-is?
3. If the bundler inserts newlines, should they be platform-dependent?

```
createBundle ...
  simple ... FAILED (43ms)
    error: AssertionError: Values are not equal:


        [Diff] Actual / Expected


        [
          {
    -       output: "file:///dist/9e45b2c928cbe2b3ac0bd66da2fdc2c60eecbb79f0b04d24bbbc1013d35f5e27.js",
    -       source: 'console.log("hello world");\r\n',
    +       output: "file:///dist/110d55de4196564d60bddda37af5e920bd8acce3c57baece085c57d002e401e9.js",
    +       source: 'console.log("hello world");\n',
          },
        ]

      throw new AssertionError(message);
            ^
        at assertEquals (https://deno.land/std@0.143.0/testing/asserts.ts:176:9)
        at fn (file:///C:/Users/dan/Documents/Cerulean/Bundler/plugins/typescript/typescript_plugin_test.ts:547:9)
        at async testStepSanitizer (deno:runtime/js/40_testing.js:450:7)
        at async asyncOpSanitizer (deno:runtime/js/40_testing.js:148:9)
        at async resourceSanitizer (deno:runtime/js/40_testing.js:376:7)
        at async exitSanitizer (deno:runtime/js/40_testing.js:433:9)
        at async TestContext.step (deno:runtime/js/40_testing.js:1416:13)
        at async fn (file:///C:/Users/dan/Documents/Cerulean/Bundler/plugins/typescript/typescript_plugin_test.ts:539:5)
```

**Comment by timreichen** [comment]
I added a .gitattributes file. EOL for files should always be LF.
I think I found a way to handle the problem for the tests: Setting `compilerOptions.newLine = ts.NewLineKind.LineFeed` so it will always generate LF independent of the os.

**Comment by rotu** [comment]
Great! The tests seem to fail on Windows still, though. BTW, you might be able to run the CI tests on a Windows runner locally using https://github.com/nektos/act:

`act -P windows-latest=mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022`

**Comment by timreichen** [comment]
Thanks, I tried to set it up with act but get `Error response from daemon: No such image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022`. However, the tests now are passing.

**Comment by rotu** [comment]
> Thanks, I tried to set it up with act but get `Error response from daemon: No such image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022`. However, the tests now are passing.

You're right and my bad. I guess act can't virtualize Windows yet.
